### ISSUE TITLE
Store cookies after consent is given

### ISSUE THREAD

**Issue by michamilz** [42coders/eu-cookie-consent#1]
This package shows a consent popup but cookies were stored before this consent is given. This is not GDPR/DSGVO compliant.

**Comment by Max-Hutschenreiter** [comment]
Hey michamilz, 

thanks for using the Package!

With the Package, you can prevent Cookies from getting created with the function  `EuCookieConsent::canIUse('key_name_of_the_cookie')`
From my understanding, it's ok to play out the cookies which are needed to run the site. But I would not recommend setting cookies which are special from a third party.

**Comment by Max-Hutschenreiter** [comment]
See my last comment
