### ISSUE TITLE
acceptAllButton not working for getUpdatePopup()

### ISSUE THREAD

**Issue by leonnicklas** [42coders/eu-cookie-consent#11]
I just saw the cool new feature where later updating the users settings were implemented. Very Nice feature!

BUT: I just found out that the `acceptAllButton` isn't working when trying to update the settings. Instead of checking all non-essential cookies and then saving the settings it just saves it without checking all available checkboxes!
If the cookie however isn't set at all and the popup shows for the first time everything works just fine.

I think i found the problem but I don't know if my workaround is the best way:

When the `getUpdatePopup()` gets called the following script tag (from the `poput.blade.php` file) doesn't get loaded into the page and therefore can not be executed:

```js
<script>
    function euCookieConsentSetCheckboxesByClassName(classname) {
        checkboxes = document.getElementsByClassName('eu-cookie-consent-cookie');
        for (i = 0; i < checkboxes.length; i++) {
            checkboxes[i].setAttribute('checked', 'checked');
            checkboxes[i].checked = true;
        }
    }
</script>
```

When duplicating the snippet and pasting it into the `update_poput.blade.php` file, everything just works fine again.

Please let me know if the problem could be fixed with an easier way, if not I would be happy to open a pull request.

**Comment by Max-Hutschenreiter** [comment]
Fixed in the v1.0.5 release thanks for letting me know about the bug.
