### ISSUE TITLE
How to add ajax validation for form

### ISSUE THREAD

**Issue by zourite** [42coders/eu-cookie-consent#3]
It's possible to make ajax validation when user accept all cookies or save changes ?

**Comment by Max-Hutschenreiter** [comment]
At the moment it's working with a redirect to the page not ajax. But I will keep it in my mind for the next version.

**Comment by simonbuehler** [comment]
yep ist somehow annoying when e.g. a registartion form is completed and gets cleared when accepting cookies because of the refresh
