### ISSUE TITLE
No checkbox

### ISSUE THREAD

**Issue by Nielswindey** [42coders/eu-cookie-consent#6]
Hi

installed the script, but users can not click a checkbox to dismiss some cookies?

![B4E82FC8-0D38-4949-BC98-2B8AF46C637D](https://user-images.githubusercontent.com/36492664/109098943-83471800-7722-11eb-9983-c8b93d8e38cc.png)

**Comment by Max-Hutschenreiter** [comment]
Hey can you please share the Config file.
