### ISSUE TITLE
Give ability to revoke or change settings

### ISSUE THREAD

**Issue by Web02Altitude** [42coders/eu-cookie-consent#8]
To be fully E.U. compliant I added a little fixed button to delete the cookie and refresh page... It would be more convenient to have that handled and possibly without refreshing.

**Comment by Max-Hutschenreiter** [comment]
Hey, can you show me a more detailed example of what you mean? I am not sure if I 100% understand which cookie you want to delete.

**Comment by meatpaste** [comment]
the end user has the right to alter/revoke the choices they have made, so to be compliant there needs to be a facility to re-launch the popup after consent has been granted

**Comment by Max-Hutschenreiter** [comment]
Its implemented in version v.1.0.4 you can now call a js function so you can add it anywhere on your site.
